#!/bin/bash
TOPBASE="$(cd "$(dirname "$0")" || exit; pwd)"

import () {
  BASE=$TOPBASE
  __FILENAME="$BASE"/"$1"
  if [ -n "$__DIRNAME" ];then 
    BASE=$__DIRNAME
    __FILENAME=$1
  fi
  __DIRNAME="$(cd "$(dirname "$__FILENAME")" || exit; pwd)"
  . "$__FILENAME"
}

command () {
  file_name () {
    basename "${1%.*}"
  }
  hyphen () {
    echo "$1" | tr '_' '-'
  }
  underscore () {
    echo "$1" | tr '-' '_'
  }
  USAGE=""
  DESC=""

  DIR="$__DIRNAME"/"$1"
  FILES="$(find "$DIR" -maxdepth 1 -type f -name '*.sh' -print | sort -t '\0' -n)"
  TUSAGE="\\n"
  USAGE=""
  DESC=""
  FOUND=false
  SUBCOMMAND=$2
  _SUBCOMMAND=$(underscore "$SUBCOMMAND")

  for FILE in $FILES; do
    if [ -f "$FILE" ]; then
      import "$FILE"
      FNAME=$(file_name "$FILE")
      PRETTYNAME=$(hyphen "$FNAME")
      BUSAGE=$(printf '%-30s' "$PRETTYNAME $USAGE")   
      TUSAGE="$TUSAGE $BUSAGE $DESC\n"
      USAGE=""
      if [ "$_SUBCOMMAND" = "$FNAME" ]; then
        FOUND=true
      fi
    fi
  done
  
  if [ "$FOUND" = true ]; then
    shift
    shift
    "$_SUBCOMMAND" "$@"
  else
    printf "Usage: <...args>\n"
    printf "$TUSAGE"
    exit 1
  fi

}

__FILENAME=$0
__DIRNAME=$TOPBASE
command ./scripts $@
