#!/bin/sh
__DIRNAME="$(cd "$(dirname "$0")" || exit; pwd)"
export __DIRNAME
__FILENAME="$__DIRNAME/$(basename "$0")"
export __FILENAME
__CMDNAME=$(basename "${__FILENAME%.*}")
export __CMDNAME
__CMDDEEP=""
export __CMDDEEP
__ROOT=$__DIRNAME
export __ROOT

import () {
  __CACHEDIRNAME="$__DIRNAME"
  __CACHEFILENAME="$__FILENAME"

  __ISABSOLUTE=false
  case $1 in
    /*) __ISABSOLUTE=true
  esac
  
  if [ "$__ISABSOLUTE" = false ]; then
    __FILENAME="$__DIRNAME/$1"
  else
    __FILENAME="$1"
  fi
  __DIRNAME="$(cd "$(dirname "$__FILENAME")" || exit; pwd)"
  
  ALIAS=""
  # shellcheck disable=SC1090
  . "$__FILENAME"
  ALIAS=""

  __DIRNAME="$__CACHEDIRNAME"
  __FILENAME="$__CACHEFILENAME"
}

command () {
  case $1 in
    /*) __DIRNAME="$(cd "$(dirname "$1")" || exit; pwd)";;
    *) __DIRNAME="$(cd "$(dirname "$__DIRNAME/$1")" || exit; pwd)";;
  esac

  __FILENAME="$__DIRNAME/$(basename "$1")"
  # echo $__FILENAME/
  __CMDNAME=$(basename "${__FILENAME%.*}")
  __FILES=$(find "$__FILENAME" -maxdepth 1 -type f -name '*.sh' -print | sort -t '\0' -n)
  
  __SCRIPTCMDNAME=$(echo $__CMDNAME | tr '_' '-')
  
  if [ "$ALIAS" != "" ]; then
    __SCRIPTCMDNAME="$ALIAS"
  fi

  if [ "$__CMDDEEP" = "" ]; then
    __CMDDEEP="$__SCRIPTCMDNAME"
  else
    __CMDDEEP="$__CMDDEEP $__SCRIPTCMDNAME"
  fi
  
  __SUBCMD=$(echo "$2" | tr '_' '-')
  __EXE=false
  __EXEFILENAME=""
  __EXEDIRNAME=""
  __HELPLINES=""
  
  USAGE=''
  ALIAS=''
  DESC=''

  for __FILENAME in $__FILES; do
    if [ -f "$__FILENAME" ]; then
      __DIRNAME="$(cd "$(dirname "$__FILENAME")" || exit; pwd)"
      __CMDNAME=$(basename "${__FILENAME%.*}") # ex. run, run_npm, ts_node
      __HUMANCMDNAME=$(echo "$__CMDNAME" | tr '_' '-')
      
      # shellcheck disable=SC1090
      . "$__FILENAME"

      if [ "$ALIAS" != "" ]; then
        __HUMANCMDNAME="$ALIAS"
      fi

      __HELPLINES="$__HELPLINES$(printf '%-30s' "$__HUMANCMDNAME $USAGE") $DESC\n"

      if [ "$__SUBCMD" = "$__HUMANCMDNAME" ]; then
        __EXEFILENAME=$__FILENAME
        __EXEDIRNAME=$__DIRNAME
        __EXE="$__CMDNAME"
      fi

      USAGE=''
      ALIAS=''
      DESC=''
    fi
  done

  if [ "$__EXE" != false ]; then
    __FILENAME="$__EXEFILENAME"
    __DIRNAME="$__EXEDIRNAME"

    shift;
    shift
    "$__EXE" "$@"
  else
    printf '%b' "Usage: $__CMDDEEP <...args>\n\n"
    printf '%b' "$__HELPLINES"
    exit 1
  fi
}

ALIAS='run'
command ./scripts "$@"
